In [1]:
%ls .

 C 드라이브의 볼륨: SSD
 볼륨 일련 번호: BCA4-98AF

 C:\Users\inhoinno\Desktop\Ordered Softeware\2021 봄\빅데이터처리_신현석\HW_BIG 디렉터리

2021-06-03  오전 01:40    <DIR>          .
2021-06-03  오전 01:40    <DIR>          ..
2021-06-02  오후 10:28    <DIR>          .ipynb_checkpoints
2021-05-31  오후 08:41         7,362,645 1920_origin.zip
2021-06-02  오후 11:05    <DIR>          1920_preprocessed
2021-05-31  오후 08:40           378,221 1920_preprocessed.zip
2021-06-02  오후 11:15    <DIR>          1920_processed
2021-06-02  오후 08:48            74,295 2020_1_total.csv
2021-06-02  오후 11:44         1,936,315 COVID_BigTable(stack).csv
2021-06-02  오후 11:44           267,356 COVID_BigTable.csv
2021-05-31  오후 06:43             8,126 Data_preprocessing_Auto.ipynb
2021-06-02  오후 08:50            58,221 Data_preprocessing1.ipynb
2021-05-31  오후 06:43            92,753 Data_preprocessing1-M45.ipynb
2021-06-02  오후 08:23    <DIR>          Data_preprocessing2-Idxing
2021-06-02  오후 08:59         2,555,166 Data_preprocessing2-Idxing.ipynb
2021-06-03  오전 01:40           574,190 Data_processing_CONCAT_MATPLOT_SEABORNv1_INHOINNO.ipynb
2021-06-03  오전 12:17            26,946 Data_processing_CONCAT_MATPLOT_SEABORNv1_INHOINNO.zip
2021-06-02  오후 03:06    <DIR>          Data_processing_reshape_total
2021-06-02  오후 11:16            57,003 Data_processing_reshape_total.ipynb
2021-06-03  오전 12:37             9,131 Data_processing_reshape_total.zip
2021-06-02  오후 10:24            40,153 Data_processing_reshape_total_2.ipynb
2021-05-31  오후 08:48            18,853 preprocessed_notebook.zip
2021-05-31  오후 08:48             1,363 Readme.md
2021-06-02  오후 09:25            38,084 sample.ipynb
2021-06-02  오후 03:00                72 Untitled.ipynb
              18개 파일          13,498,893 바이트
               7개 디렉터리  20,502,011,904 바이트 남음

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Load Data with Multi-level indexing
pseudo code : 
* for FILE in range(2019_1, 2020_12)
    * FILE = './1920_processed/{year}_{month}_processed.csv'.format(year=Y, month=M) 
    * olddata = newdata
    * newdata = pd.read_csv(FILE,encoding='utf-8')
    * newdata['year'] = Y 
    * newdata['month'] = M
    * newdata = newdata.set_index(['year','month', 'A. 도시명'])
    * newdata.index.names=['year','month','city']
    * newdata = newdata.sort_index()
    * pd.concat([olddata,newdata], axis=0)

In [53]:
Y=2019
M=1
olddata = pd.DataFrame()
newdata = pd.DataFrame()

In [54]:
# File
while(Y<2021):
    FILE = './1920_processed/{year}_{month}_processed.csv'.format(year=Y, month=M) 
    
    # Read CSV
    #if(Y==2019 & M ==1):
    newdata = pd.read_csv(FILE,encoding='utf-8')
    newdata = newdata.drop(columns = newdata.columns[0])
    #else:
        #olddata = newdata
        #newdata = pd.read_csv(FILE,encoding='utf-8')
        #newdata = data.drop(columns = data.columns[0])
        
    #MultiIndexing 
    newdata['year'] = Y
    newdata['month'] = M
    newdata = newdata.set_index(['year','month','A. 도시명'])
    newdata.index.names=['year','month','city']
    newdata = newdata.sort_index()
    
    if (Y==2019 & M ==1):
        olddata = newdata
    else :
        olddata = pd.concat([olddata,newdata], axis = 0)
    print('{0}_{1} fin'.format(Y,M))
    # increment
    if(M + 1 >= 13): # M=12 Next year
        M = 1
        Y += 1
    else :     
        M += 1

2019_1 fin
2019_2 fin
2019_3 fin
2019_4 fin
2019_5 fin
2019_6 fin
2019_7 fin
2019_8 fin
2019_9 fin
2019_10 fin
2019_11 fin
2019_12 fin
2020_1 fin
2020_2 fin
2020_3 fin
2020_4 fin
2020_5 fin
2020_6 fin
2020_7 fin
2020_8 fin
2020_9 fin
2020_10 fin
2020_11 fin
2020_12 fin

In [55]:
olddata

                      B. 업종전체    가구점  가스충전소 가전제품수리점 가전제품판매점    간이주점  간판광고물업  \
year month city
2019 1     강원도         82,677    300     93     465     444     439     505
           경기도        520,472  1,873    372   3,694   1,810   2,997   3,113
           경상남도       152,758    564    151     790     727   1,314     685
           경상북도       125,481    461    163     489     693     409     641
           광주광역시       67,965    214     41     393     339     188     443
...                       ...    ...    ...     ...     ...     ...     ...
2020 12    전라북도        88,047    411    111     573     530     272     511
           제주특별자치도     47,390    191     34     194     250     156     197
           충청남도       106,102    299    130     705     532     544     479
           충청북도        80,408    275     74     495     412     391     383
           합계       2,548,586  7,650  1,611  16,962  10,186  12,219  12,996

                    감정평가사 건강보조식품가게  건어물가게  ...     편의점 피부ㆍ비뇨기과 의원   피부관리업  \
year month city                            ...
2019 1     강원도         29      496    667  ...   1,589         58     951
           경기도        358    2,496    797  ...   9,558        793   7,548
           경상남도        56      988    723  ...   2,804        165   2,399
           경상북도        19      886    658  ...   1,808         98   1,390
           광주광역시       32      397    167  ...   1,010        126   1,406
...                   ...      ...    ...  ...     ...        ...     ...
2020 12    전라북도        39      734    360  ...   1,335         97   1,405
           제주특별자치도     16      180    110  ...   1,200         44     794
           충청남도        38    1,272    635  ...   2,383         99   1,487
           충청북도        32      435    108  ...   1,615         81   1,256
           합계       1,234   13,988  7,381  ...  44,858      4,071  42,168

                      피시방  한방병원ㆍ한의원    한식전문점   헬스클럽   호프전문점   화장품가게   휴대폰가게
year month city
2019 1     강원도        420       357   19,271    205   1,485   1,070     588
           경기도      2,413     3,155   77,957  1,680   7,127   7,771   3,901
           경상남도       678       807   31,752    386   1,539   2,434   1,292
           경상북도       593       635   29,086    343   1,068   1,871   1,086
           광주광역시      426       416    9,558    216   2,406   1,118     588
...                   ...       ...      ...    ...     ...     ...     ...
2020 12    전라북도       391       541   14,620    244   1,124   1,474     722
           제주특별자치도    168       199    9,068    136     605     664     244
           충청남도       452       517   20,013    292   1,391   1,356     886
           충청북도       359       406   15,764    276   1,533     985     551
           합계       9,970    14,947  397,465  8,569  29,002  35,004  18,737

[432 rows x 101 columns]

In [56]:
olddata.loc[(slice('2020','2020'),slice(None),),:]['B. 업종전체'] #2020년 1~12월 지역별 업종전체 사업자 수

year  month  city
2020  1      강원도          85,671
             경기도         558,878
             경상남도        157,493
             경상북도        129,486
             광주광역시        70,997
                          ...
      12     전라북도          88,047
             제주특별자치도       47,390
             충청남도         106,102
             충청북도          80,408
             합계         2,548,586
Name: B. 업종전체, Length: 216, dtype: object

In [57]:
olddata.loc[(slice('2020','2020'),slice(12,12),),:]['B. 업종전체'] #2020년 2월 지역별 업종전체 사업자 수

year  month  city
2020  12     강원도           89,174
             경기도          607,611
             경상남도         164,113
             경상북도         134,420
             광주광역시         73,840
             대구광역시        120,587
             대전광역시         73,542
             부산광역시        166,264
             서울특별시        508,188
             세종특별자치시       14,380
             울산광역시         53,737
             인천광역시        131,544
             전라남도          89,239
             전라북도          88,047
             제주특별자치도       47,390
             충청남도         106,102
             충청북도          80,408
             합계         2,548,586
Name: B. 업종전체, dtype: object

In [58]:
arr = olddata.loc[(slice('2020','2020'),slice(12,12), slice('강원도','충청북도')),:]['B. 업종전체'].values

In [59]:
olddata = olddata.replace('*','0')
olddata = olddata.replace(' * ','0')
olddata = olddata.fillna(0)

In [60]:
#remove ' ,' 
olddata = olddata.replace(',','', regex=True)
# str to uin
olddata =olddata.astype(int)

In [61]:
type(olddata.values[1][1])

numpy.int32

In [62]:
olddata.to_csv('./COVID_BigTable.csv',sep=',',encoding='utf-8')

In [63]:
olddata.columns.names = ['corp']

In [64]:
pd.DataFrame(olddata.stack(level=-1)).to_csv('./COVID_BigTable(stack).csv',sep=',',encoding='utf-8')